version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
        - POSTGRES_USER=postmill
        - POSTGRES_PASSWORD=secret
  php:
    image: registry.gitlab.com/postmill/postmill/app
    restart: always
    environment:
        - TRUSTED_HOSTS=my.postmill.site.tld
    volumes:
        - postmill_images:/app/public/submission_images
        - postmill_thumbs:/app/public/media/cache
        - postmill_var:/app/var
  web:
    image: registry.gitlab.com/postmill/postmill/web
    restart: always
    environment:
        - TRUSTED_HOSTS=my.postmill.site.tld
    ports:
        - "3002:80"
    volumes:
        - postmill_images:/app/public/submission_images \
        - postmill_thumbs:/app/public/media/cache \
volumes:
    postmill_images: {}
    postmill_thumbs: {}
    postmill_var: {}

